/**
 * The palette, made switchable — imported wholesale from GEXYGEN.
 *
 * WHY IMPORTED RATHER THAN REINVENTED. GEXYGEN's `lib/theme.ts` is where the
 * work actually happened: seventeen hues, each with eight tiers generated as
 * fixed lightness and chroma targets in OKLCH and clamped into sRGB per tier,
 * every one contrast-checked against the surface #11131a before it was written
 * down. Ink, dteInk and ladInk clear 4.5:1; no offered hue lands within 30
 * degrees of the flip's amber, so a themed wall can never be mistaken for the
 * flip line. None of that is worth doing twice, and doing it twice would mean
 * two palettes that drift.
 *
 * GENERATED by server/tools/build_theme.py. Edit that, not this.
 *
 * EVERY TIER IS A LITERAL HEX, NOT A `color-mix()`. GEXYGEN needs that because
 * it reads tokens with `getComputedStyle().getPropertyValue()` and hands them
 * to a canvas, which would receive an unresolved `color-mix(...)` string and
 * draw nothing. This terminal has no canvas today — but the constraint costs
 * nothing and the sparklines are one refactor from wanting it.
 *
 * WHAT WAS DROPPED ON THE WAY ACROSS: GEXYGEN's `posCall`/`posPut` (its
 * Positioning card, the only place a side hue is drawn at partial strength) and
 * `volCool`/`volMid`/`volHot` (the ATM IV heat ramp). Neither has anything to
 * bind to here.
 *
 * WHAT IS DELIBERATELY NOT THEMED: the five desk hues on the wire. They are
 * identity tags on a 3px rail, they have to stay distinguishable from each
 * other at equal value, and letting a preset recolour them would let a headline
 * rail collide with the up/down palette.
 */

export type HueId =
  | "green" | "pink" | "cyan" | "blue" | "purple" | "red" | "crimson"
  | "orange" | "lime" | "cobalt" | "indium" | "iodine" | "sulphur"
  | "amber" | "white" | "silver" | "slate";

export interface Hue {
  id: HueId;
  name: string;
  /** Chart fills and strokes — the identity value. */
  mark: string;
  /** Body-text tier, >=4.5:1 on --surface. */
  ink: string;
  /** The large figures. */
  fig: string;
  /** Glow and decoration — the brightest tier. */
  neon: string;
  /** Stepped-back variants of the same hue. */
  dte: string;
  dteInk: string;
  /** Heavily desaturated, side-tinted. */
  lad: string;
  ladInk: string;
  /** The near-white sheen stop the wordmark gradient routes through. */
  lift: string;
}

export type DuoMode = "solid" | "duo";

export interface ThemeChoice {
  /* --- data: these hues mean something --- */
  /** Calls, positive gamma, and up. */
  call: HueId;
  /** Puts, negative gamma, and down. */
  put: HueId;
  /** The gamma flip, and anything demanding attention. */
  flip: HueId;
  /** Spot and the figures that carry no side. */
  neutral: HueId;

  /* --- chrome: decoration, and free to be anything --- */
  /** The active tab's underline. */
  tabs: HueId;
  /** The two rings of the mark. */
  iconA: HueId;
  iconB: HueId;
  titleMode: DuoMode;
  titleA: HueId;
  titleB: HueId;
  /** The wordmark's third stop — a hue's `lift` tier, never its neon. */
  sheen: HueId;
  frameMode: DuoMode;
  frameA: HueId;
  frameB: HueId;
}

export const HUES: readonly Hue[] = [
  {
    id: "green",
    name: "Green",
    mark: "#00ac77",
    ink: "#00ac77",
    fig: "#19e3a4",
    neon: "#00ffb2",
    dte: "#0a7d5a",
    dteInk: "#2f9a76",
    lad: "#3f6b5c",
    ladInk: "#7fa294",
    lift: "#7ff0d0",
  },
  {
    id: "lime",
    name: "Lime",
    mark: "#599300",
    ink: "#75b32e",
    fig: "#8dd242",
    neon: "#91e71c",
    dte: "#447200",
    dteInk: "#679736",
    lad: "#4a6038",
    ladInk: "#8a9c7c",
    lift: "#b7ed88",
  },
  {
    id: "cyan",
    name: "Cyan",
    mark: "#0090a6",
    ink: "#31b0c8",
    fig: "#46cee9",
    neon: "#3de1ff",
    dte: "#007081",
    dteInk: "#3a94a6",
    lad: "#3b5f67",
    ladInk: "#7f9ba2",
    lift: "#8fe9fe",
  },
  {
    id: "blue",
    name: "Blue",
    mark: "#4275f7",
    ink: "#6d9aff",
    fig: "#99baff",
    neon: "#b1caff",
    dte: "#385db7",
    dteInk: "#5b82db",
    lad: "#45577f",
    ladInk: "#8595b6",
    lift: "#c7d9ff",
  },
  {
    id: "purple",
    name: "Purple",
    mark: "#9551f4",
    ink: "#ae80ff",
    fig: "#c4a9ff",
    neon: "#d2beff",
    dte: "#7245b6",
    dteInk: "#946cd9",
    lad: "#5e4e7e",
    ladInk: "#998eb6",
    lift: "#ded0ff",
  },
  {
    id: "pink",
    name: "Pink",
    mark: "#bc2071",
    ink: "#ef6ba6",
    fig: "#ff6fb4",
    neon: "#ff4fa3",
    dte: "#8e2a5e",
    dteInk: "#c56395",
    lad: "#6b3f55",
    ladInk: "#a8869a",
    lift: "#ffb0d8",
  },
  /*
   * RED, DEEPENED (owner instruction, 2026-08-16 — "needs to be a bit darker").
   *
   * The first pass put red on the same mid-lightness recipe as the rest, which
   * gave a `fig` of #ff9a96 — a pale salmon that reads as pink before it reads
   * as red, and sat badly beside the actual pink. It is on the deep recipe now:
   * the mark drops to #bb0026 and the figure tier lands on a genuine red.
   */
  {
    id: "red",
    name: "Red",
    mark: "#bb0026",
    ink: "#ff3d4c",
    fig: "#ff7070",
    neon: "#ff9591",
    dte: "#94001c",
    dteInk: "#eb434c",
    lad: "#753837",
    ladInk: "#b78380",
    lift: "#ffc3bf",
  },
  /*
   * CRIMSON — the deep end of the red family, restored for the Scarlet preset.
   *
   * H=12 against Red's 23 and Pink's 355: inside the 40-degree floor of both,
   * so `separated` correctly refuses to pair it against either — it is Red's
   * deeper sibling exactly as Cobalt is Blue's.
   *
   * ITS TEXT TIERS ARE DELIBERATELY OFF THE GAMUT EDGE. Generated at full
   * chroma the way Indium is, `ink` came out #fb005f — a hot magenta-pink that
   * reads as neither crimson nor red, because this arc goes fluorescent as it
   * climbs PAST L~0.63. Ink and the muted tiers are pulled back to ~72% of
   * maximum, which keeps the family resemblance to the #960036 mark. Contrast
   * is slightly better for it, not worse: ink 4.83:1 on the card surface.
   *
   * `fig` AND `neon` ARE PINNED DEEP AND CONVERGED, the same end state indium
   * reached after its calibrations (owner instruction, 2026-08-16: crimson's
   * bright appearances should sit near the tape bar, not at dusty rose). Both
   * are #dc0053 — L=0.57 at FULL chroma, which is legal here because the
   * fluorescence problem only starts above L~0.63; at 0.57 the hue still
   * reads as blood. That lands the rail figure and dots at 3.68:1 (floor 3:1
   * for 26px text and marks) and pulls the wordmark end, ring, comet, tab
   * underline, down-candles and glows to the same value. `lift` steps to the
   * ramp's barC so the wash keeps a lighter neighbour.
   */
  {
    id: "crimson",
    name: "Crimson",
    mark: "#960036",
    ink: "#e04e6b",
    fig: "#dc0053",
    neon: "#dc0053",
    dte: "#760028",
    dteInk: "#dc536d",
    lad: "#5f3339",
    ladInk: "#b57980",
    lift: "#dd7f90",
  },
  {
    id: "orange",
    name: "Orange",
    mark: "#c95c00",
    ink: "#e87e3e",
    fig: "#ff9f69",
    neon: "#ffb891",
    dte: "#9b480d",
    dteInk: "#bf6e3f",
    lad: "#734e3a",
    ladInk: "#ad8e7d",
    lift: "#ffcdb2",
  },
  /*
   * THE DEEP THREE, and why they are not just "Blue" and "Purple" again.
   *
   * Cobalt sits 4 degrees from Blue and Iodine 5 from Purple — as hues they are
   * the same colours. What differs is DEPTH: the generated set targets a fixed
   * lightness per tier, which is what keeps eight hues consistent with each
   * other, and the cost of that consistency is that every one of them lands in
   * the same airy register. These three are built on a lower-lightness,
   * higher-chroma recipe instead, so Cobalt reads as ink-dark saturated blue
   * beside Blue's daylight, and Iodine as a jewel against Purple's lavender.
   * Being near-identical in hue is why `separated` blocks pairing them with
   * their neighbours — correctly, since hue is what the eye sorts a map by.
   *
   * Sulphur breaks the recipe in the other direction, because it has to.
   * Yellow's gamut peaks near L=0.9; at the deep recipe's L=0.50 it came out
   * #726400, an olive that no one would call vibrant. It gets a bright recipe,
   * which is not an inconsistency so much as an acknowledgement that "vivid
   * yellow" and "vivid blue" do not live at the same lightness.
   *
   * Named for the elements, which the oxygen-molecule mark started. Cobalt blue
   * is a pigment, iodine vapour really is that violet, and sulphur really is
   * that yellow.
   */
  {
    id: "cobalt",
    name: "Cobalt",
    mark: "#0059d3",
    ink: "#498eff",
    fig: "#6ca4ff",
    neon: "#8cb8ff",
    dte: "#0045a7",
    dteInk: "#4986ea",
    lad: "#364d73",
    ladInk: "#8093b2",
    lift: "#bcd6ff",
  },
  /*
   * INDIUM — deeper again than Cobalt, and the reason there are two.
   *
   * Cobalt is a saturated blue that still sits in the mid-lightness band every
   * other hue occupies. This one drops the mark to L=0.48 near the gamut
   * edge, which puts the bar's ANCHOR far below every text tier —
   * 2.53:1 against the card, deliberately. That is only viable because the bar
   * is a gradient: `barA` starts near this mark and `barC` finishes near the
   * neon at 8.4:1, so a long bar still reads clearly while its root sinks into
   * the chassis. It is the "deep" look asked for (owner instruction,
   * 2026-08-16) rather than merely another blue.
   *
   * The text tiers do NOT follow it down — `ink` and `dteInk` both had to be
   * lifted to clear 4.5:1, and `dteInk` failed at 4.39 on the first pass. Depth
   * is a property of the marks here, not of the type.
   *
   * Named for its indigo spectral line, which is where the element got its own
   * name — the same reasoning as Cobalt, Iodine and Sulphur.
   */
  {
    id: "indium",
    name: "Indium",
    /*
     * THE MARK IS PINNED TO ITS OWN barA STOP, after three calibrations of the
     * same pixel row (owner instructions, 2026-08-16). Today's Tape is the one
     * surface that paints the raw mark flat at full alpha — everything else
     * shows it at 15-16% opacity or through the CHART_STOPS gradients — so
     * "the mark" is in practice "the tape bar", and the sequence ran:
     *
     *   #3e00dc  L=0.43 C=0.267   generated       "a bit dark"
     *   #4500f1  L=0.46 C=0.286   lighter, richer "lighter and LESS rich"
     *   #562ae5  L=0.48 C=0.254   = barA          <- here
     *
     * Landing on barA rather than a fourth arbitrary point means the tape bar
     * now sits on exactly the anchor every other put bar in the app grows
     * from — one root colour, not two. If it still reads heavy, the next
     * principled stop up the same ramp is barB #7765f1.
     *
     * Still fractionally deeper than cobalt's mark at L=0.50, so the preset's
     * "deepest blue" claim survives, barely and knowingly.
     */
    mark: "#562ae5",
    ink: "#6e75ff",
    /*
     * PINNED DARKER THAN THE RECIPE — L=0.58 rather than 0.69, and the number
     * is the result of TWO calibrations against the same eye (owner
     * instructions, 2026-08-16). The generated #828eff was a pale periwinkle
     * with no family resemblance to the deep indium mark; the first pin went to
     * L=0.55 (#564dff, "the richer darker version") and came back a tad too
     * dark. L=0.58 is the midpoint of that bracket, still at the sRGB chroma
     * maximum for its lightness, so it keeps the richness that was the point.
     *
     * Chroma could not close the gap on its own: measured, indium's tiers were
     * already at the gamut edge for their lightness, so lightness was the only
     * lever either direction.
     *
     * WHAT SETS THE FLOOR is what consumes `fig` — the 26px rail figures, the
     * side dots, and the Positioning tone. Every one is large text or a
     * graphical mark, so the bar is 3:1 rather than the 4.5:1 that governs body
     * copy. This lands on 3.99:1, clear with margin.
     *
     * `ink` DID NOT MOVE and cannot. The small numbers and the rank chevrons
     * run on it at 4.5:1, and indium's ink is already within 0.5 of that floor.
     *
     * SCOPED BY ACCIDENT OF USE: indium appears in exactly one preset
     * (Cyberpunk), so pinning the hue is in practice a Cyberpunk-only change.
     * Cobalt and Iodine stay on the generated recipe — they were offered the
     * same treatment and it was reverted, so the divergence here is deliberate
     * rather than an oversight.
     */
    fig: "#5e5eff",
    /*
     * NEON PINNED TO THE MARK — the fourth and widest indium calibration
     * (owner instruction, 2026-08-16: the indium travelling across the
     * wordmark should match the tape bar's darkness and richness). The
     * generated #9da9ff was the palest tier of a hue whose entire point is
     * depth, and it was the last bright indium left on the Cyberpunk screen.
     *
     * NEON IS A SHARED TIER, so this deliberately deepens every indium glow
     * surface at once, not just the word: the down-candle bodies (now the
     * same violet as the tape bar, which the owner reads fine on the same
     * dark ground), the put-side glow halos and glitch split (subtler now),
     * the icon's large ring and the favicon, and the frame comet's head —
     * which the owner explicitly wanted indium-led, and now actually reads
     * as the deep hue rather than a pastel stand-in for it.
     *
     * SECOND CALIBRATION, same day: the first pin put neon ON the mark
     * (#562ae5) and the owner asked for a bit lighter across all of it. It
     * now sits on #5e5eff — which is exactly indium's `fig`, and that
     * convergence is the tidy end state rather than an accident: indium has
     * two working values now, the deep #562ae5 for flat bars and #5e5eff for
     * everything that shines (figures, dots, word, ring, comet, candles,
     * glows). The candles and glow halos also gain real contrast from the
     * lift, 2.53:1 -> 3.99:1.
     *
     * `lift` follows one gradient stop up (barC) so the wordmark wash keeps a
     * lighter neighbour to travel through. CHART_STOPS stay on the original
     * bright ramp on purpose — the profile bars' lift toward pale violet has
     * never been the complaint. If any single casualty here turns out to
     * matter, splitting it back out needs a per-slot tier override, not
     * another value change — see the consumer list in themeVars.
     */
    neon: "#5e5eff",
    dte: "#2f00ae",
    dteInk: "#6e75ff",
    lad: "#363b77",
    ladInk: "#8089b8",
    // barC of the chart ramp — one stop above the pinned neon, so the wordmark
    // wash still has a lighter neighbour to shine through. See the neon note.
    lift: "#8f90fa",
  },
  {
    id: "iodine",
    name: "Iodine",
    mark: "#8d10c8",
    ink: "#ba61f3",
    fig: "#ca7bff",
    neon: "#d59aff",
    dte: "#6c1b97",
    dteInk: "#aa64d9",
    lad: "#5a416c",
    ladInk: "#9d89ad",
    lift: "#e6c5ff",
  },
  {
    id: "sulphur",
    name: "Sulphur",
    mark: "#e3c800",
    ink: "#eed200",
    fig: "#fddf00",
    neon: "#ffea6d",
    dte: "#a79300",
    dteInk: "#c3ab00",
    lad: "#8a8150",
    ladInk: "#b2ac87",
    lift: "#fff09e",
  },
  /*
   * The last two are CHROME-ONLY — see HUE_SETS below. Neither is offered for
   * calls or puts, for different reasons: amber is the flip's own hue and a
   * wall wearing it would be indistinguishable from the regime boundary, and
   * white is spot's, besides being achromatic in a place where hue is the only
   * thing separating the two sides of the book.
   *
   * Both are PINNED to their shipping values rather than generated. The recipe
   * that produced the six new chromatic hues targets a fixed lightness, which
   * drags amber down to a dull #a67700 — nothing like the #c9962e that ships as
   * --flip. Same argument as green and pink: the default has to be the value
   * that is already on screen, not an approximation of it.
   */
  {
    id: "amber",
    name: "Amber",
    mark: "#c9962e",
    ink: "#c9962e",
    fig: "#ffc857",
    neon: "#ffd24a",
    dte: "#7f5c12",
    dteInk: "#a28042",
    lad: "#65563b",
    ladInk: "#a0937e",
    lift: "#ffe6a8",
  },
  {
    id: "white",
    name: "White",
    mark: "#dfe3ec",
    ink: "#f2f4f8",
    fig: "#f2f4f8",
    neon: "#ffffff",
    dte: "#7d8088",
    dteInk: "#9b9ea6",
    lad: "#57585b",
    ladInk: "#949597",
    // #e6f4f3, not #ffffff — this is the exact near-white the wordmark
    // gradient has always used at its midpoint, and white is the default sheen,
    // so the default lockup stays byte-identical.
    lift: "#e6f4f3",
  },
  /*
   * THE TWO GREYS, which exist so a palette can have no colour in it at all.
   *
   * They are steps of LIGHTNESS, not of hue — there is no hue to step. Placed
   * by hand against the existing ink ramp rather than generated, with a trace
   * of blue (chroma 0.008 at H=265) so they belong to the same family as --ink
   * at #f2f4f8 rather than reading as a dead neutral grey dropped in beside it.
   *
   * Together with White they give three clear stations — 16.9:1, 9.9:1 and
   * 6.4:1 on the card — which is what makes an all-grey theme legible at all.
   * See `separated` for how a pair of these is checked, since the hue rule that
   * governs every other pair has nothing to measure here.
   */
  {
    id: "silver",
    name: "Silver",
    mark: "#84868b",
    ink: "#a2a5aa",
    fig: "#bbbec3",
    neon: "#d5d7dd",
    dte: "#5b5e62",
    dteInk: "#909297",
    lad: "#505257",
    ladInk: "#96989d",
    lift: "#e8ebf1",
  },
  {
    id: "slate",
    name: "Slate",
    mark: "#53555a",
    ink: "#818388",
    fig: "#96989d",
    neon: "#aeb1b6",
    dte: "#3b3d41",
    dteInk: "#818388",
    lad: "#404247",
    ladInk: "#8a8c91",
    lift: "#ced1d6",
  },
];

const BY_ID = new Map(HUES.map((h) => [h.id, h]));

export function isHueId(v: unknown): v is HueId {
  return typeof v === "string" && BY_ID.has(v as HueId);
}

/** A hue by id, falling back rather than throwing — a bad cookie is not fatal. */
export function hue(id: HueId | string | undefined, fallback: HueId): Hue {
  return BY_ID.get(id as HueId) ?? BY_ID.get(fallback)!;
}

export const DEFAULT_THEME: ThemeChoice = {
  call: "green",
  put: "pink",
  flip: "amber",
  neutral: "white",
  tabs: "amber",
  iconA: "green",
  iconB: "pink",
  titleMode: "duo",
  titleA: "green",
  titleB: "pink",
  sheen: "white",
  frameMode: "duo",
  frameA: "green",
  frameB: "pink",
};

export interface Preset {
  id: string;
  name: string;
  blurb?: string;
  theme: ThemeChoice;
  /** The shipping palette, and what the reset control restores. */
  isDefault?: true;
}

export const PRESETS: readonly Preset[] = [
  {
    id: "original",
    name: "Aurora",
    /*
     * Named for the actual phenomenon, not for being first. Green and magenta
     * is the aurora's own emission palette — and the green is atomic OXYGEN,
     * which is the molecule in the mark and the back half of the product's
     * name. Of the twelve it is still the only one that could be named for
     * something GEXYGEN already was.
     */
    theme: DEFAULT_THEME,
    isDefault: true,
  },
  {
    id: "ember",
    name: "Ember",
    /*
     * REBUILT to be warm, which the name always promised and the palette never
     * delivered (owner instruction, 2026-08-16). It was CYAN calls against red
     * puts — half the map was the coldest hue in the set, under a name meaning
     * a glowing coal. The old blurb admitted it: "the coldest and hottest ends".
     *
     * An ember is a temperature gradient, so the two sides are now the two ends
     * of one: sulphur where it is hottest and red where it has cooled. That is
     * also the widest warm pair available — 77 degrees — because orange sits 27
     * from red and amber 18 from sulphur, so nothing else on the warm arc can
     * carry two sides at once.
     *
     * THE FLIP IS CYAN, and that is not a leftover. Every warm hue is inside
     * the floor of one side or the other, so the flip had to leave the arc —
     * and the hottest part of a flame really is blue, so the one cool line on a
     * warm map is the part that is hotter than all of it.
     */
    theme: {
      call: "sulphur",
      put: "red",
      flip: "cyan",
      neutral: "white",
      tabs: "orange",
      iconA: "sulphur",
      iconB: "red",
      titleMode: "duo",
      titleA: "sulphur",
      titleB: "red",
      sheen: "amber",
      frameMode: "duo",
      frameA: "sulphur",
      frameB: "red",
    },
  },
  {
    id: "scarlet",
    name: "Crimson",
    /*
     * The red theme (owner request, 2026-08-16), built STARK: crimson is the
     * only colour anywhere. Calls are white, neutrals step down to silver so
     * the two stay distinct (Chromium's own arrangement), and the flip is a
     * red line one shade brighter than the blood it crosses. Half the profile
     * runs red against a monochrome field; the red IS the theme.
     *
     * THE RED FLIP RIDES A NAMED EXCEPTION. Red sits 10 degrees off the
     * crimson puts — inside the 40-degree floor — and the first build refused
     * it and used slate. The owner overrode that with the reasoning on record
     * ("allow me to do this because they are noticeably different shades"),
     * and the judgement holds at the tiers that actually render: flip figure
     * #ff7070 against put figure #dc0053, flip line #bb0026 against bands at
     * #960036 — depth separates what hue cannot. See FLIP_EXCEPTIONS, which
     * is deliberately a pair list and not a loosened floor: the SIDES rule
     * did not move.
     *
     * DE-GOLDED earlier the same day; the chassis is crimson and white only —
     * blood word washing to bone (neon and fig pinned to #dc0053, "deeper,
     * like its tape bar"), a crimson comet head on a white tail, a crimson
     * tab underline.
     *
     * NAMED CRIMSON, MATCHING THE HUE, on the owner's explicit call — made
     * with the Chrome/Chromium name-collision precedent pointed out and
     * declined. The preset id stays "scarlet" (ids are internal; Aurora's is
     * still "original"), so the heat-allowlist key and matchPreset are
     * untouched by the rename.
     */
    theme: {
      call: "white",
      put: "crimson",
      flip: "red",
      neutral: "silver",
      /*
       * THE GOLD COOL STOP SURVIVES, and it is worth writing down why, because
       * it looks like the last piece of the de-golding and it cannot be.
       *
       * A crimson-family ramp was tried (2026-08-17) and is banned outright:
       * this palette's data hues are white, crimson and red, so a ramp inside
       * the family lands on one of them by definition — orange -> red ->
       * crimson puts the put hue at the terminus. Pink would dodge the test at
       * 17 degrees off crimson, which is the near-twin move the allowlist note
       * explicitly refuses. That leaves sulphur, amber and orange as the only
       * legal stops, and the ramp needs its lightest tier at the quiet end.
       *
       * So the gold is not an oversight in a de-golded preset; it is the only
       * place a thermometer is allowed to start here.
       */
      tabs: "crimson",
      iconA: "crimson",
      iconB: "white",
      titleMode: "duo",
      titleA: "crimson",
      titleB: "white",
      sheen: "white",
      // Crimson SECOND, because the comet's head is `--frame-b` and the tail
      // fades through `--frame-a` (owner instruction, 2026-08-16: the travel
      // effect leads with crimson) — a blood-red head trailing bone white,
      // the same head-slot reading Cyberpunk uses for indium.
      frameMode: "duo",
      frameA: "white",
      frameB: "crimson",
    },
  },
  {
    id: "ultraviolet",
    name: "Plasma",
    /*
     * RENAMED FROM ULTRAVIOLET (owner instruction, 2026-08-17). Ultraviolet
     * named the one thing that is not on the screen. UV is invisible by
     * definition, and the note below is emphatic that the lamp is the ambient
     * CONDITION rather than content — so the name pointed at the wavelength
     * and left the reader to infer the sight, in a set where Ember, Nebula and
     * Midnight all hand it over whole.
     *
     * Plasma names the visible state instead, and the palette is what an
     * ionised gas actually emits: green and magenta are the two commonest
     * emission lines — the same atomic oxygen green that Aurora is named for —
     * over the violet field of a discharge. A plasma globe is that picture in
     * one object: magenta filaments in a violet glow.
     *
     * THE OVERLAP WITH ARC IS REAL AND KNOWN, not an oversight: an electric
     * arc IS a plasma, so the two presets now name one physics from two sides —
     * Arc the discharge, Plasma the state it is in. That is the Nocturne and
     * Midnight situation again (see Cyberpunk), and it is left standing here
     * only because Arc's own name is under review. If Arc keeps it, this is the
     * pair to settle next.
     *
     * The id stays "ultraviolet" — ids are internal, the way Aurora's is still
     * "original" and Crimson's is still "scarlet" — so matchPreset and any
     * key that reads the id are untouched by the rename.
     *
     * SECOND CORRECTION the same day, and the one that gets the physics right.
     * The first rebuild put the LAMP on a side — iodine as the puts — which
     * made half the book the light source and left the fluorescence story
     * covering only the calls. Under a blacklight the lamp is the ambient
     * CONDITION and the pigments are the content: so the two sides are now the
     * two things that fluoresce, lime and magenta, and iodine moves to the
     * flip — the lamp as the structural line the content glows either side of.
     *
     * Lime to pink is 136 degrees. Iodine clears them by 179 and 45 — the 45
     * against pink is the working margin, and it is the price of a genuinely
     * violet lamp: everything deeper on that arc is inside pink's floor.
     */
    theme: {
      call: "lime",
      put: "pink",
      flip: "iodine",
      neutral: "white",
      tabs: "iodine",
      iconA: "iodine",
      iconB: "lime",
      titleMode: "duo",
      titleA: "iodine",
      titleB: "lime",
      sheen: "white",
      frameMode: "duo",
      frameA: "iodine",
      frameB: "lime",
    },
  },
  {
    id: "daylight",
    name: "Daylight",
    /*
     * Named for the pair, not for a place. Blue and orange is the combination
     * that survives red-green colour blindness — the reason it is in the set at
     * all — and it is sky-and-sun besides, which makes it the one preset that
     * reads as full light beside Midnight.
     *
     * THE FLIP IS GREEN, not the pink it shipped with. Pink against sky-and-sun
     * is a DUSK colour — the tint the sky takes when the day is ending, the
     * opposite of what this preset is named for. Green is the daylight third:
     * foliage under sun, 102 degrees from blue and 113 from orange, clear of
     * both by nearly double what the pink managed on its tight side.
     *
     * THE HEAT RAMP RUNS sulphur -> AMBER -> red rather than the standard
     * orange mid stop, because orange is the put here and an exact clash is
     * banned. Yellow to gold to red reads as the same thermometer, and the
     * swap retired the allowlist entry this preset used to need — the clash
     * was only unavoidable while the mid stop had to be orange.
     */
    theme: {
      call: "blue",
      put: "orange",
      flip: "green",
      neutral: "white",
      tabs: "amber",
      iconA: "blue",
      iconB: "orange",
      titleMode: "duo",
      titleA: "blue",
      titleB: "orange",
      sheen: "white",
      frameMode: "duo",
      frameA: "blue",
      frameB: "orange",
    },
  },
  {
    id: "arc",
    name: "Arc",
    /*
     * Renamed from Voltaic (owner instruction, 2026-08-16). "Voltaic" pointed
     * at the right idea through a word most people meet once, in a footnote
     * about a pile of zinc discs. An electric arc is the same physics and the
     * thing you can actually picture — and it is what the palette looks like:
     * a cobalt discharge with a sulphur-bright core and a violet fringe.
     */
    theme: {
      call: "cobalt",
      put: "sulphur",
      flip: "iodine",
      neutral: "white",
      /*
       * WHITE COOL STOP, not the usual sulphur, because sulphur IS the put
       * here. The heat ramp is warm on every preset but Chromium — a
       * thermometer earns its value from being invariant — and the exception
       * is drawn narrowly: not "near a data hue" but EXACTLY one, on the
       * common reading. Sulphur is the cool stop, so a quiet tape would have
       * shown ATM IV in the same yellow as every put wall, on ordinary days
       * rather than rare ones. White through orange to red keeps the ascent.
       */
      tabs: "sulphur",
      iconA: "cobalt",
      iconB: "sulphur",
      titleMode: "duo",
      titleA: "cobalt",
      titleB: "sulphur",
      sheen: "sulphur",
      frameMode: "duo",
      frameA: "cobalt",
      frameB: "sulphur",
    },
  },
  {
    id: "cyberpunk",
    name: "Cyberpunk",
    /*
     * Renamed from Nocturne (owner instruction, 2026-08-16), and the palette
     * had already grown into it: acid yellow over the deepest blue in the set,
     * with a magenta crossing between them. That trio is the genre's whole
     * colour scheme, and the pink flip added just before this is what completed
     * it — as Nocturne the preset was named for the dark and had stopped being
     * mostly dark.
     *
     * It also settles a collision that was left standing on purpose: Nocturne
     * and Midnight were both named for night and sat two chips apart. Only one
     * of them is now.
     */
    theme: {
      /*
       * THE SIDES ARE THE OTHER WAY ROUND from every other preset, and that is
       * the point of it rather than an oversight. Arc puts the cold hue on
       * calls because that is the convention the original set; here the bright
       * warm hue carries calls and the deep blue sinks the put side into the
       * chassis. Nothing in the app assumes which side is brighter — the two
       * are told apart by hue, not by weight — so the inversion costs nothing
       * and reads completely differently.
       */
      call: "sulphur",
      put: "indium",
      /*
       * PINK — the third answer here, and the best separated of them (owner
       * instruction, 2026-08-16). It went red, then cyan, then this.
       *
       * Red was legal and loud, the wrong note on a palette whose whole
       * character is depth. Cyan was picked as the only COOL hue clear of
       * indium, which was true but only just: 60 degrees, the tightest gap in
       * the preset. Pink sits 79 from indium and 104 from sulphur, so the flip
       * line is now further from both sides than it has been on either of the
       * previous attempts.
       *
       * It also stops the map being entirely cold. Sulphur carries the calls
       * warm and indium takes the puts deep; a magenta crossing between them is
       * the one hue that belongs to neither side.
       */
      flip: "pink",
      neutral: "white",
      // White, not sulphur — sulphur is the CALL here. Same reasoning as
      // Arc above: the clash is exact and lands on the quiet, common state.
      tabs: "sulphur",
      iconA: "indium",
      iconB: "sulphur",
      titleMode: "duo",
      titleA: "indium",
      titleB: "sulphur",
      sheen: "sulphur",
      /*
       * REVERSED against the other presets, so INDIUM LEADS the trail (owner
       * instruction, 2026-08-16). The frame light's comet takes its head from
       * `--frame-b` and fades its tail through `--frame-a` — see the note on
       * `.app-frame::after` — so the leading colour is the SECOND slot, not the
       * first. Sulphur first, indium second, deep blue at the head.
       */
      frameMode: "duo",
      frameA: "sulphur",
      frameB: "indium",
    },
  },
  {
    id: "midnight",
    name: "Midnight",
    /*
     * CALLS MOVED FROM CYAN TO COBALT (owner instruction, 2026-08-16). Cyan is
     * an electric, daylit blue — it read as a lit sign rather than as midnight,
     * and it was the brightest thing on a palette whose entire idea is that the
     * flip should be. Cobalt is the deep end of the same family, so both sides
     * now sit dark and the white flip is unambiguously the only bright element.
     *
     * Cobalt against iodine is 50 degrees, the tightest legal pair here, which
     * is the price of keeping both sides deep: everything deeper is inside the
     * floor of one or the other.
     */
    theme: {
      /*
       * A NIGHT PALETTE THAT IS NOT JUST ANOTHER BLUE ONE. Arc, Cyberpunk
       * and Nebula all lean on the deep end of the wheel already, so this earns
       * its place a different way: it is the only preset where the FLIP is the
       * brightest element on the map. Both sides sit in the cold half — cyan
       * against iodine, 94 degrees apart — and pure white crosses them, which
       * is what a single lit line over dark water looks like.
       *
       * That inverts the usual weighting on purpose. Everywhere else the two
       * sides shout and the flip is a third voice; here the sides are the quiet
       * field and the boundary is the thing you cannot miss.
       */
      call: "cobalt",
      put: "iodine",
      flip: "white",
      // Silver, not white — the neutral figures have to sit BELOW the flip on a
      // palette whose whole idea is that the flip is brightest.
      neutral: "silver",
      /*
       * COLD TO HOT ALONG THE PALETTE'S OWN ARC, rather than the standard gold.
       * Both sides here sit in the cold half, so a yellow quiet reading was the
       * only warm thing on the screen and it read as borrowed. Cyan is 44 from
       * cobalt, so it is clear of the calls; the walk then climbs through violet
       * into magenta, which is the direction this palette already runs.
       *
       * THE FLIP IS STILL THE BRIGHTEST THING, which is the preset's premise:
       * pink's ink is #ef6ba6 against a pure white flip, so the hot reading is
       * saturated without out-lighting the line it must not out-light.
       *
       * THE MID STOP IS A NEAR-TWIN OF THE PUTS, and that is the cost of this
       * ramp rather than a thing that was missed. Purple sits 5 degrees off
       * iodine, so at middling volatility the figure is in the puts' hue —
       * the same shape of collision UNAVOIDABLE_HEAT_CLASH exists to record.
       * It is not on that list because it is not an exact match, and it is
       * accepted rather than dodged for two reasons: the whole cold arc from
       * cobalt to iodine is this palette's own, so every possible mid stop is
       * a near-twin of one side or the other, and the two tiers that actually
       * render are far apart in depth — purple's fig is #c4a9ff, a pale
       * lavender, against iodine's #ca7bff jewel. If it reads badly in use the
       * answer is to drop back to the standard warm ramp, not to hunt for a
       * cleaner cold one; there isn't one.
       */
      tabs: "cobalt",
      iconA: "iodine",
      iconB: "cobalt",
      titleMode: "duo",
      titleA: "iodine",
      titleB: "cobalt",
      sheen: "silver",
      // Iodine second, so the deeper hue leads the comet — same reading as
      // Cyberpunk, where the head is `--frame-b`.
      frameMode: "duo",
      frameA: "cobalt",
      frameB: "iodine",
    },
  },
  {
    id: "chromium",
    name: "Chromium",
    theme: {
      /*
       * THE ONE PALETTE WITH NO HUE IN IT, and worth being honest about what
       * that costs. Every other preset separates the two sides by colour, which
       * is the fastest channel the eye has. This one separates them by
       * LIGHTNESS — near-white calls against dark-grey puts, 0.43 apart in
       * OKLCH — and leans on the two things that were always doing part of the
       * work anyway: call bars grow right and put bars grow left, and every
       * figure sits under a label that names its side.
       *
       * It is slower to read than Aurora. It is also the only one that puts
       * nothing between you and the shape of the book, which is the point
       * (owner instruction, 2026-08-16 — "very neutral and not in your face").
       *
       * The flip takes the middle station rather than the brightest, because
       * the brightest belongs to the calls; a flip that outshone both sides on
       * a map this quiet would be the loudest thing on screen.
       */
      call: "white",
      put: "slate",
      flip: "silver",
      neutral: "silver",
      tabs: "silver",
      iconA: "slate",
      iconB: "silver",
      // Slate into white, which is what chrome actually looks like: a dark
      // reflection running up into a highlight.
      titleMode: "duo",
      titleA: "slate",
      titleB: "white",
      sheen: "silver",
      frameMode: "solid",
      frameA: "silver",
      frameB: "silver",
    },
  },
  {
    id: "nebula",
    name: "Nebula",
    theme: {
      call: "cobalt",
      put: "pink",
      flip: "iodine",
      neutral: "white",
      /*
       * Same cold start as Midnight, for the same reason: the palette occupies
       * the arc from cobalt through iodine to pink, so cyan is the one cold hue
       * left to begin on and the climb runs along the palette's own colours.
       *
       * THE HOT STOP IS RED RATHER THAN PINK, unlike Midnight's. Pink is the
       * PUT here, so the magenta terminus that works there is an exact clash
       * with a data hue on this palette. Red keeps the alarm and keeps the ramp
       * off the allowlist; the cost is one long step at the top.
       *
       * The mid stop carries the same near-twin cost as Midnight's — purple is
       * 5 degrees off iodine — but lands on the FLIP here rather than on a
       * side, which is the cheaper of the two collisions: one line against a
       * column of bars. See the note on Midnight for why no cleaner cold mid
       * stop exists on either palette.
       */
      tabs: "iodine",
      iconA: "iodine",
      iconB: "pink",
      titleMode: "duo",
      titleA: "cobalt",
      titleB: "pink",
      sheen: "iodine",
      frameMode: "duo",
      frameA: "iodine",
      frameB: "pink",
    },
  },
  {
    id: "vapour",
    name: "Vapour",
    /*
     * The flip moves amber -> purple (2026-08-16). Vapour was always the
     * vaporwave preset — hot pink on cyan with a solid neon frame — but the
     * amber flip was a note from outside the genre entirely. The vaporwave
     * triad is pink, cyan and PURPLE: purple sits 50 from pink and 89 from
     * cyan, legal on both sides, and it is the one hue that makes the set read
     * as the genre rather than as two colours borrowed from it. Tabs go cyan
     * for the same reason — teal-on-pink is the genre's own contrast.
     */
    theme: {
      call: "pink",
      put: "cyan",
      flip: "purple",
      neutral: "white",
      /*
       * THE STANDARD RAMP STAYS, after trying to give this one the genre's own
       * blue-purple-pink sky (2026-08-17). Every stop of that sky is a data hue
       * here — purple is the flip, pink the calls, cyan the puts — and the only
       * way to make it pass was iodine for purple, five degrees apart, which is
       * precisely the near-twin dodge UNAVOIDABLE_HEAT_CLASH refuses to accept.
       * With cyan taken there is no cold hue left to start a clean walk from.
       *
       * It is also the least foreign of the four this was reviewed with: gold
       * over orange into red is a sunset, which is the genre's own sky anyway.
       */
      tabs: "cyan",
      iconA: "pink",
      iconB: "cyan",
      titleMode: "duo",
      titleA: "pink",
      titleB: "cyan",
      sheen: "pink",
      frameMode: "solid",
      frameA: "pink",
      frameB: "cyan",
    },
  },
  {
    id: "matrix",
    name: "Matrix",
    /*
     * Green over slate under a white flip (owner request, 2026-08-17), and the
     * only preset where the calls carry the entire colour budget.
     *
     * It is the near-inverse of Chromium: that one runs monochrome and lets
     * lightness do all the separating, this one keeps the same grey field and
     * spends its one hue on the call side. So the two sides separate on the
     * PRESENCE of colour rather than on a hue pair, which is the widest
     * separation available — and the reason the CVD question does not arise
     * here at all, since there is only one hue to confuse.
     *
     * THE FLIP IS WHITE AND THE NEUTRAL SILVER, the arrangement Midnight
     * settled on: the boundary has to sit above the ordinary figures, and on a
     * palette this quiet a white flip is unmissable without being loud. Slate
     * to silver is 0.17 in lightness, the closest legal achromatic pair, which
     * is the price of getting three grey stations out of a palette that spends
     * its hue elsewhere.
     *
     * The heat ramp is the standard one and clean on this palette — sulphur
     * sits 63 degrees off the green calls and the greys have no angle to clash
     * with, so nothing here needed the treatment Arc and Cyberpunk did.
     */
    theme: {
      call: "green",
      put: "slate",
      flip: "white",
      neutral: "silver",
      tabs: "green",
      iconA: "slate",
      iconB: "green",
      // Slate rising into green, the way Chromium runs slate into white: a dark
      // field with the one live colour coming up out of it.
      titleMode: "duo",
      titleA: "slate",
      titleB: "green",
      sheen: "white",
      frameMode: "duo",
      frameA: "slate",
      frameB: "green",
    },
  },
];

/** The preset this theme exactly matches, if any. */
export function matchPreset(t: ThemeChoice): Preset | undefined {
  const keys = Object.keys(DEFAULT_THEME) as (keyof ThemeChoice)[];
  return PRESETS.find((p) => keys.every((k) => p.theme[k] === t[k]));
}

/**
 * A theme -> the custom properties globals.css reads.
 *
 * ONLY THE TOKENS THIS TERMINAL ACTUALLY DEFINES. GEXYGEN emits about forty;
 * these are every themed token in globals.css. Emitting one it does not define
 * would be a value nothing reads, which is how a stylesheet and a theme quietly
 * stop agreeing.
 */
export function themeVars(t: ThemeChoice): Record<string, string> {
  const call = hue(t.call, "green");
  const put = hue(t.put, "pink");
  const flip = hue(t.flip, "amber");
  const neutral = hue(t.neutral, "white");
  const tabs = hue(t.tabs, "amber");
  const iconA = hue(t.iconA, "green");
  const iconB = hue(t.iconB, "pink");
  const titleA = hue(t.titleA, "green");
  // Solid mode is not a token: the gradient runs between two identical stops,
  // so nothing downstream needs to know a mode exists.
  const titleB = hue(t.titleMode === "solid" ? t.titleA : t.titleB, "pink");
  const sheen = hue(t.sheen, "white");
  const frameA = hue(t.frameA, "green");
  const frameB = hue(t.frameMode === "solid" ? t.frameA : t.frameB, "pink");

  return {
    "--call": call.mark,
    "--put": put.mark,
    "--flip": flip.mark,
    "--spot": neutral.ink,
    "--call-dte": call.dte,
    "--put-dte": put.dte,
    "--neon-call": call.neon,
    "--neon-put": put.neon,
    "--neon-flip": flip.neon,
    "--tab-accent": tabs.neon,
    "--icon-a": iconA.neon,
    "--icon-b": iconB.neon,
    "--title-a": titleA.neon,
    "--title-a-lift": titleA.lift,
    "--title-b": titleB.neon,
    "--title-b-lift": titleB.lift,
    "--title-sheen": sheen.lift,
    "--frame-a": frameA.neon,
    "--frame-b": frameB.neon,
  };
}

/** The same, as a React style object for `<html>`. */
export function themeStyle(t: ThemeChoice): React.CSSProperties {
  return themeVars(t) as React.CSSProperties;
}

/**
 * Parse a stored theme, keeping only values this build knows.
 *
 * EVERY FIELD FALLS BACK INDEPENDENTLY, so a cookie written by a later build
 * that adds a slot degrades to the default for that one slot rather than
 * throwing the whole theme away.
 */
export function parseTheme(raw: string | undefined): ThemeChoice {
  if (!raw) return DEFAULT_THEME;
  let v: Record<string, unknown>;
  try {
    v = JSON.parse(decodeURIComponent(raw)) as Record<string, unknown>;
  } catch {
    return DEFAULT_THEME;
  }
  const pick = (k: keyof ThemeChoice): HueId =>
    isHueId(v[k]) ? (v[k] as HueId) : (DEFAULT_THEME[k] as HueId);
  const mode = (k: "titleMode" | "frameMode"): DuoMode =>
    v[k] === "solid" || v[k] === "duo" ? (v[k] as DuoMode) : DEFAULT_THEME[k];
  return {
    call: pick("call"),
    put: pick("put"),
    flip: pick("flip"),
    neutral: pick("neutral"),
    tabs: pick("tabs"),
    iconA: pick("iconA"),
    iconB: pick("iconB"),
    titleMode: mode("titleMode"),
    titleA: pick("titleA"),
    titleB: pick("titleB"),
    sheen: pick("sheen"),
    frameMode: mode("frameMode"),
    frameA: pick("frameA"),
    frameB: pick("frameB"),
  };
}

export const THEME_COOKIE = "nt_theme";
