"""One-shot: build src/lib/theme.ts from GEXYGEN's palette.

Kept in the repo rather than run and thrown away, because the day GEXYGEN
regenerates a hue tier this is how the two are brought back into step — and
because the list of slots deliberately dropped on the way across is the kind of
decision that needs to be findable.

    python server/tools/build_theme.py  [path-to-gexygen]
"""

from __future__ import annotations

import os
import re
import sys

GEX = sys.argv[1] if len(sys.argv) > 1 else r"C:\Users\61411\Desktop\GEXYGEN"
HERE = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))

# Slots GEXYGEN has and this terminal has nothing to bind to: the Positioning
# card's own side pair, and the ATM-IV heat ramp. Carried as dead fields they
# would send a reader looking for a card that does not exist here.
DROP = ("posCall", "posPut", "volCool", "volMid", "volHot")

HEAD = '''/**
 * The palette, made switchable — imported wholesale from GEXYGEN.
 *
 * WHY IMPORTED RATHER THAN REINVENTED. GEXYGEN's `lib/theme.ts` is where the
 * work actually happened: seventeen hues, each with eight tiers generated as
 * fixed lightness and chroma targets in OKLCH and clamped into sRGB per tier,
 * every one contrast-checked against the surface #11131a before it was written
 * down. Ink, dteInk and ladInk clear 4.5:1; no offered hue lands within 30
 * degrees of the flip's amber, so a themed wall can never be mistaken for the
 * flip line. None of that is worth doing twice, and doing it twice would mean
 * two palettes that drift.
 *
 * GENERATED by server/tools/build_theme.py. Edit that, not this.
 *
 * EVERY TIER IS A LITERAL HEX, NOT A `color-mix()`. GEXYGEN needs that because
 * it reads tokens with `getComputedStyle().getPropertyValue()` and hands them
 * to a canvas, which would receive an unresolved `color-mix(...)` string and
 * draw nothing. This terminal has no canvas today — but the constraint costs
 * nothing and the sparklines are one refactor from wanting it.
 *
 * WHAT WAS DROPPED ON THE WAY ACROSS: GEXYGEN's `posCall`/`posPut` (its
 * Positioning card, the only place a side hue is drawn at partial strength) and
 * `volCool`/`volMid`/`volHot` (the ATM IV heat ramp). Neither has anything to
 * bind to here.
 *
 * WHAT IS DELIBERATELY NOT THEMED: the five desk hues on the wire. They are
 * identity tags on a 3px rail, they have to stay distinguishable from each
 * other at equal value, and letting a preset recolour them would let a headline
 * rail collide with the up/down palette.
 */

export type HueId =
  | "green" | "pink" | "cyan" | "blue" | "purple" | "red" | "crimson"
  | "orange" | "lime" | "cobalt" | "indium" | "iodine" | "sulphur"
  | "amber" | "white" | "silver" | "slate";

export interface Hue {
  id: HueId;
  name: string;
  /** Chart fills and strokes — the identity value. */
  mark: string;
  /** Body-text tier, >=4.5:1 on --surface. */
  ink: string;
  /** The large figures. */
  fig: string;
  /** Glow and decoration — the brightest tier. */
  neon: string;
  /** Stepped-back variants of the same hue. */
  dte: string;
  dteInk: string;
  /** Heavily desaturated, side-tinted. */
  lad: string;
  ladInk: string;
  /** The near-white sheen stop the wordmark gradient routes through. */
  lift: string;
}

export type DuoMode = "solid" | "duo";

export interface ThemeChoice {
  /* --- data: these hues mean something --- */
  /** Calls, positive gamma, and up. */
  call: HueId;
  /** Puts, negative gamma, and down. */
  put: HueId;
  /** The gamma flip, and anything demanding attention. */
  flip: HueId;
  /** Spot and the figures that carry no side. */
  neutral: HueId;

  /* --- chrome: decoration, and free to be anything --- */
  /** The active tab's underline. */
  tabs: HueId;
  /** The two rings of the mark. */
  iconA: HueId;
  iconB: HueId;
  titleMode: DuoMode;
  titleA: HueId;
  titleB: HueId;
  /** The wordmark's third stop — a hue's `lift` tier, never its neon. */
  sheen: HueId;
  frameMode: DuoMode;
  frameA: HueId;
  frameB: HueId;
}

'''

MID = '''
const BY_ID = new Map(HUES.map((h) => [h.id, h]));

export function isHueId(v: unknown): v is HueId {
  return typeof v === "string" && BY_ID.has(v as HueId);
}

/** A hue by id, falling back rather than throwing — a bad cookie is not fatal. */
export function hue(id: HueId | string | undefined, fallback: HueId): Hue {
  return BY_ID.get(id as HueId) ?? BY_ID.get(fallback)!;
}

export const DEFAULT_THEME: ThemeChoice = {
  call: "green",
  put: "pink",
  flip: "amber",
  neutral: "white",
  tabs: "amber",
  iconA: "green",
  iconB: "pink",
  titleMode: "duo",
  titleA: "green",
  titleB: "pink",
  sheen: "white",
  frameMode: "duo",
  frameA: "green",
  frameB: "pink",
};

export interface Preset {
  id: string;
  name: string;
  blurb?: string;
  theme: ThemeChoice;
  /** The shipping palette, and what the reset control restores. */
  isDefault?: true;
}

'''

TAIL = '''
/** The preset this theme exactly matches, if any. */
export function matchPreset(t: ThemeChoice): Preset | undefined {
  const keys = Object.keys(DEFAULT_THEME) as (keyof ThemeChoice)[];
  return PRESETS.find((p) => keys.every((k) => p.theme[k] === t[k]));
}

/**
 * A theme -> the custom properties globals.css reads.
 *
 * ONLY THE TOKENS THIS TERMINAL ACTUALLY DEFINES. GEXYGEN emits about forty;
 * these are every themed token in globals.css. Emitting one it does not define
 * would be a value nothing reads, which is how a stylesheet and a theme quietly
 * stop agreeing.
 */
export function themeVars(t: ThemeChoice): Record<string, string> {
  const call = hue(t.call, "green");
  const put = hue(t.put, "pink");
  const flip = hue(t.flip, "amber");
  const neutral = hue(t.neutral, "white");
  const tabs = hue(t.tabs, "amber");
  const iconA = hue(t.iconA, "green");
  const iconB = hue(t.iconB, "pink");
  const titleA = hue(t.titleA, "green");
  // Solid mode is not a token: the gradient runs between two identical stops,
  // so nothing downstream needs to know a mode exists.
  const titleB = hue(t.titleMode === "solid" ? t.titleA : t.titleB, "pink");
  const sheen = hue(t.sheen, "white");
  const frameA = hue(t.frameA, "green");
  const frameB = hue(t.frameMode === "solid" ? t.frameA : t.frameB, "pink");

  return {
    "--call": call.mark,
    "--put": put.mark,
    "--flip": flip.mark,
    "--spot": neutral.ink,
    "--call-dte": call.dte,
    "--put-dte": put.dte,
    "--neon-call": call.neon,
    "--neon-put": put.neon,
    "--neon-flip": flip.neon,
    "--tab-accent": tabs.neon,
    "--icon-a": iconA.neon,
    "--icon-b": iconB.neon,
    "--title-a": titleA.neon,
    "--title-a-lift": titleA.lift,
    "--title-b": titleB.neon,
    "--title-b-lift": titleB.lift,
    "--title-sheen": sheen.lift,
    "--frame-a": frameA.neon,
    "--frame-b": frameB.neon,
  };
}

/** The same, as a React style object for `<html>`. */
export function themeStyle(t: ThemeChoice): React.CSSProperties {
  return themeVars(t) as React.CSSProperties;
}

/**
 * Parse a stored theme, keeping only values this build knows.
 *
 * EVERY FIELD FALLS BACK INDEPENDENTLY, so a cookie written by a later build
 * that adds a slot degrades to the default for that one slot rather than
 * throwing the whole theme away.
 */
export function parseTheme(raw: string | undefined): ThemeChoice {
  if (!raw) return DEFAULT_THEME;
  let v: Record<string, unknown>;
  try {
    v = JSON.parse(decodeURIComponent(raw)) as Record<string, unknown>;
  } catch {
    return DEFAULT_THEME;
  }
  const pick = (k: keyof ThemeChoice): HueId =>
    isHueId(v[k]) ? (v[k] as HueId) : (DEFAULT_THEME[k] as HueId);
  const mode = (k: "titleMode" | "frameMode"): DuoMode =>
    v[k] === "solid" || v[k] === "duo" ? (v[k] as DuoMode) : DEFAULT_THEME[k];
  return {
    call: pick("call"),
    put: pick("put"),
    flip: pick("flip"),
    neutral: pick("neutral"),
    tabs: pick("tabs"),
    iconA: pick("iconA"),
    iconB: pick("iconB"),
    titleMode: mode("titleMode"),
    titleA: pick("titleA"),
    titleB: pick("titleB"),
    sheen: pick("sheen"),
    frameMode: mode("frameMode"),
    frameA: pick("frameA"),
    frameB: pick("frameB"),
  };
}

export const THEME_COOKIE = "nt_theme";
'''


def grab(lines: list[str], marker: str) -> str:
    i = next(k for k, line in enumerate(lines) if line.startswith(marker))
    j = next(k for k in range(i, len(lines)) if lines[k].rstrip() == "];")
    return "".join(lines[i : j + 1])


def main() -> None:
    src_path = os.path.join(GEX, "src", "lib", "theme.ts")
    with open(src_path, encoding="utf-8") as f:
        lines = f.read().splitlines(keepends=True)

    hues = grab(lines, "export const HUES")
    presets = grab(lines, "export const PRESETS")
    for slot in DROP:
        presets = re.sub(rf"^\s*{slot}: \"[a-z]+\",\n", "", presets, flags=re.M)

    out = os.path.join(HERE, "src", "lib", "theme.ts")
    with open(out, "w", encoding="utf-8", newline="") as f:
        f.write(HEAD + hues + MID + presets + TAIL)

    n_h = len(re.findall(r'^\s{4}id: "', hues, flags=re.M))
    n_p = re.findall(r'^\s{4}id: "([a-z]+)"', presets, flags=re.M)
    print(f"wrote {out}")
    print(f"  {n_h} hues, {len(n_p)} presets: {', '.join(n_p)}")


if __name__ == "__main__":
    main()
