import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    ignores: [
      "server/**",
      ".next/**",
      "node_modules/**",
      // Generated by Next on every build. Its triple-slash reference is
      // exactly what the framework writes, so linting it only ever produces
      // an error about someone else's file.
      "next-env.d.ts",
    ],
  },
];

export default config;
